# Generated by Django 5.2.5 on 2026-03-18 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncaa_player_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('team_org_id', models.IntegerField(db_index=True)),
                ('team_name', models.CharField(max_length=200)),
                ('academic_year', models.IntegerField(db_index=True)),
                ('division', models.IntegerField()),
                ('jersey_number', models.CharField(blank=True, max_length=10)),
                ('position', models.CharField(blank=True, max_length=20)),
                ('class_year', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'indexes': [models.Index(fields=['academic_year', 'division', 'team_org_id'], name='dashboard_p_academi_1419c3_idx')],
            },
        ),
        migrations.CreateModel(
            name='GameLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_date', models.DateField(null=True)),
                ('opponent_name', models.CharField(max_length=200)),
                ('opponent_org_id', models.IntegerField(blank=True, null=True)),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('shots', models.IntegerField(default=0)),
                ('shots_on_goal', models.IntegerField(default=0)),
                ('ground_balls', models.IntegerField(default=0)),
                ('turnovers', models.IntegerField(default=0)),
                ('caused_turnovers', models.IntegerField(default=0)),
                ('faceoffs_won', models.IntegerField(default=0)),
                ('faceoffs_lost', models.IntegerField(default=0)),
                ('saves', models.IntegerField(blank=True, null=True)),
                ('goals_allowed', models.IntegerField(blank=True, null=True)),
                ('minutes_played', models.FloatField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_logs', to='dashboard.player')),
            ],
            options={
                'indexes': [models.Index(fields=['game_date'], name='dashboard_g_game_da_db596e_idx')],
            },
        ),
        migrations.CreateModel(
            name='SeasonTotals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games_played', models.IntegerField(default=0)),
                ('games_started', models.IntegerField(default=0)),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('shots', models.IntegerField(default=0)),
                ('shots_on_goal', models.IntegerField(default=0)),
                ('ground_balls', models.IntegerField(default=0)),
                ('turnovers', models.IntegerField(default=0)),
                ('caused_turnovers', models.IntegerField(default=0)),
                ('faceoffs_won', models.IntegerField(default=0)),
                ('faceoffs_lost', models.IntegerField(default=0)),
                ('saves', models.IntegerField(blank=True, null=True)),
                ('goals_allowed', models.IntegerField(blank=True, null=True)),
                ('minutes_played', models.FloatField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_totals', to='dashboard.player')),
            ],
            options={
                'indexes': [models.Index(fields=['player'], name='dashboard_s_player__dbcbd3_idx')],
            },
        ),
    ]
